Close: Decoupled state transition and the handling of the request.
eleme/doctor pull request #14
Opened 2016-12-26 12:23 UTC by JustScrapy

Decoupled state transition and the handling of the request.
PR for [issue #13 ](https://github.com/eleme/doctor/issues/13)

2016-12-27 12:21 UTC, damnever requested changes

2016-12-27 12:21 UTC, damnever commented on doctor/checker.py
> +            elif not self._metrics.api_latest_state.get(key, False):
Typing a few more lines of code could be better :-）
```Python
if api_latest_state_ok():
    if time_passed:
        pass
else:
    pass
```

```Python
latest_state_ok = api_latest_state_ok()
if latest_state and time_passed:
    pass
else not latest_state:
    pass

2016-12-27 12:21 UTC, damnever commented on doctor/checker.py
> +        elif locked_status == MODE_UNLOCKED and \
https://www.python.org/dev/peps/pep-0008/#multiline-if-statements

2016-12-27 12:21 UTC, damnever commented
LGTM

2016-12-28 03:43 UTC, JustScrapy commented on doctor/checker.py
> +            elif not self._metrics.api_latest_state.get(key, False):
+1

2017-01-11 11:01 UTC, damnever approved these changes

2018-08-10 02:44 UTC, closed without merging